on: push
jobs:
  start:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    
    steps:
    - run: |
        pip install flake8
        flake8 .
  test:
    name: Test with pytest
    runs-on: ubuntu-latest
    steps:
    -  run: |
        pip install pytest
        pytest tests --doctest-modules --junitxml=junit/test-results.xml
